set hive.mapred.mode = nonstrict;
set mapreduce.job.queuename = q_dc_dw;


select *
from dc_dwd.qyc_temp_01;


-- 横版
drop table dc_dwd.qyc_temp_02;
create table dc_dwd.qyc_temp_02 as
with t1 as
         (select level_6,
                 concat_ws(',', collect_list(index_value)) as value,
                 concat_ws(',', collect_list(score))       as score_1
          from dc_dwd.qyc_temp_01
          group by level_6),
     t2 as (select level_6,
                   split(value, ',')[0]    as all_nation,         -- `全国`,
                   split(value, ',')[1]    as beijing,            -- `北京`,
                   split(value, ',')[2]    as tianjin,            -- `天津`,
                   split(value, ',')[3]    as hebei,              -- `河北`,
                   split(value, ',')[4]    as shanxi_1,           -- `山西`,
                   split(value, ',')[5]    as neimenggu,          -- `内蒙古`,
                   split(value, ',')[6]    as liaoning,           -- `辽宁`,
                   split(value, ',')[7]    as jilin,              -- `吉林`,
                   split(value, ',')[8]    as heilongjiang,       -- `黑龙江`,
                   split(value, ',')[9]    as shandong,           -- `山东`,
                   split(value, ',')[10]   as henan,              -- `河南`,
                   split(value, ',')[11]   as shanggai,           -- `上海`,
                   split(value, ',')[12]   as jiangsu,            -- `江苏`,
                   split(value, ',')[13]   as zhejiang,           -- `浙江`,
                   split(value, ',')[14]   as anhui,              -- `安徽`,
                   split(value, ',')[15]   as fujian,             -- `福建`,
                   split(value, ',')[16]   as jiangxi,            -- `江西`,
                   split(value, ',')[17]   as hubei,              -- `湖北`,
                   split(value, ',')[18]   as hunan,              -- `湖南`,
                   split(value, ',')[19]   as guangdong,          -- `广东`,
                   split(value, ',')[20]   as guangxi,            -- `广西`,
                   split(value, ',')[21]   as hainan,             -- `海南`,
                   split(value, ',')[22]   as chongqing,          -- `重庆`,
                   split(value, ',')[23]   as sichuan,            -- `四川`,
                   split(value, ',')[24]   as guizhou,            -- `贵州`,
                   split(value, ',')[25]   as yunnan,             -- `云南`,
                   split(value, ',')[26]   as xizang,             -- `西藏`,
                   split(value, ',')[27]   as shanxi_2,           -- `陕西`,
                   split(value, ',')[28]   as gansu,              -- `甘肃`,
                   split(value, ',')[29]   as qinghai,            -- `青海`,
                   split(value, ',')[30]   as ningxia,            -- `宁夏`,
                   split(value, ',')[31]   as xinjiang,           -- `新疆`
                   split(score_1, ',')[0]  as all_nation_score,   -- `全国`,
                   split(score_1, ',')[1]  as beijing_score,      -- `北京`,
                   split(score_1, ',')[2]  as tianjin_score,      -- `天津`,
                   split(score_1, ',')[3]  as hebei_score,        -- `河北`,
                   split(score_1, ',')[4]  as shanxi_1_score,     -- `山西`,
                   split(score_1, ',')[5]  as neimenggu_score,    -- `内蒙古`,
                   split(score_1, ',')[6]  as liaoning_score,     -- `辽宁`,
                   split(score_1, ',')[7]  as jilin_score,        -- `吉林`,
                   split(score_1, ',')[8]  as heilongjiang_score, -- `黑龙江`,
                   split(score_1, ',')[9]  as shandong_score,     -- `山东`,
                   split(score_1, ',')[10] as henan_score,        -- `河南`,
                   split(score_1, ',')[11] as shanggai_score,     -- `上海`,
                   split(score_1, ',')[12] as jiangsu_score,      -- `江苏`,
                   split(score_1, ',')[13] as zhejiang_score,     -- `浙江`,
                   split(score_1, ',')[14] as anhui_score,        -- `安徽`,
                   split(score_1, ',')[15] as fujian_score,       -- `福建`,
                   split(score_1, ',')[16] as jiangxi_score,      -- `江西`,
                   split(score_1, ',')[17] as hubei_score,        -- `湖北`,
                   split(score_1, ',')[18] as hunan_score,        -- `湖南`,
                   split(score_1, ',')[19] as guangdong_score,    -- `广东`,
                   split(score_1, ',')[20] as guangxi_score,      -- `广西`,
                   split(score_1, ',')[21] as hainan_score,       -- `海南`,
                   split(score_1, ',')[22] as chongqing_score,    -- `重庆`,
                   split(score_1, ',')[23] as sichuan_score,      -- `四川`,
                   split(score_1, ',')[24] as guizhou_score,      -- `贵州`,
                   split(score_1, ',')[25] as yunnan_score,       -- `云南`,
                   split(score_1, ',')[26] as xizang_score,       -- `西藏`,
                   split(score_1, ',')[27] as shanxi_2_score,     -- `陕西`,
                   split(score_1, ',')[28] as gansu_score,        -- `甘肃`,
                   split(score_1, ',')[29] as qinghai_score,      -- `青海`,
                   split(score_1, ',')[30] as ningxia_score,      -- `宁夏`,
                   split(score_1, ',')[31] as xinjiang_score      -- `新疆`
            from t1)
select distinct level_1,
                level_2,
                level_3,
                level_4,
                level_5,
                t2.level_6,
                is_5_window,
                importance,
                index_code,
                index_type,
                target_db_rule,
                target_value,
                index_unit,
                bz_name,
                is_offline,
                jsgs,
                monthid,
                l4_qz,
                l5_qz,
                l6_qz,
                l4_l6_qz,
                all_nation,--全国
                beijing,--北京
                tianjin,--天津
                hebei,--河北
                shanxi_1,--山西
                neimenggu,--内蒙古
                liaoning,--辽宁
                jilin,--吉林
                heilongjiang,--黑龙江
                shandong,--山东
                henan,--河南
                shanggai,--上海
                jiangsu,--江苏
                zhejiang,--浙江
                anhui,--安徽
                fujian,--福建
                jiangxi,--江西
                hubei,--湖北
                hunan,--湖南
                guangdong,--广东
                guangxi,--广西
                hainan,--海南
                chongqing,--重庆
                sichuan,--四川
                guizhou,--贵州
                yunnan,--云南
                xizang,--西藏
                shanxi_2,--陕西
                gansu,--甘肃
                qinghai,--青海
                ningxia,--宁夏
                xinjiang,--新疆
                all_nation_score,
                beijing_score,
                tianjin_score,
                hebei_score,
                shanxi_1_score,
                neimenggu_score,
                liaoning_score,
                jilin_score,
                heilongjiang_score,
                shandong_score,
                henan_score,
                shanggai_score,
                jiangsu_score,
                zhejiang_score,
                anhui_score,
                fujian_score,
                jiangxi_score,
                hubei_score,
                hunan_score,
                guangdong_score,
                guangxi_score,
                hainan_score,
                chongqing_score,
                sichuan_score,
                guizhou_score,
                yunnan_score,
                xizang_score,
                shanxi_2_score,
                gansu_score,
                qinghai_score,
                ningxia_score,
                xinjiang_score
from t2
         left join dc_dwd.qyc_temp_01 dsseio on t2.level_6 = dsseio.level_6
;


select *
from dc_dwd.qyc_temp_02;
-- 无数据 转化为100分
select level_1,
       level_2,
       level_3,
       level_4,
       level_5,
       level_6,
       is_5_window,
       importance,
       index_code,
       index_type,
       target_db_rule,
       target_value,
       index_unit,
       bz_name,
       is_offline,
       jsgs,
       monthid,
       l4_qz,
       l5_qz,
       l6_qz,
       l4_l6_qz,
       all_nation,
       beijing,
       tianjin,
       hebei,
       shanxi_1,
       neimenggu,
       liaoning,
       jilin,
       heilongjiang,
       shandong,
       henan,
       shanggai,
       jiangsu,
       zhejiang,
       anhui,
       fujian,
       jiangxi,
       hubei,
       hunan,
       guangdong,
       guangxi,
       hainan,
       chongqing,
       sichuan,
       guizhou,
       yunnan,
       xizang,
       shanxi_2,
       gansu,
       qinghai,
       ningxia,
       xinjiang,
       if(all_nation_score in ('--','无数据') and beijing_score != '不参与计算' ,100,all_nation_score ) as all_nation_score,
       if(beijing_score in ('--','无数据') and beijing_score != '不参与计算' ,100,beijing_score ) as beijing_score,
       if(tianjin_score in ('--','无数据') and beijing_score != '不参与计算' ,100,tianjin_score ) as tianjin_score,
       if(hebei_score in ('--','无数据') and beijing_score != '不参与计算' ,100,hebei_score ) as hebei_score,
       if(shanxi_1_score in ('--','无数据') and beijing_score != '不参与计算' ,100,shanxi_1_score ) as shanxi_1_score,
       if(neimenggu_score in ('--','无数据') and beijing_score != '不参与计算' ,100,neimenggu_score ) as neimenggu_score,
       if(liaoning_score in ('--','无数据') and beijing_score != '不参与计算' ,100,liaoning_score ) as liaoning_score,
       if(jilin_score in ('--','无数据') and beijing_score != '不参与计算' ,100,jilin_score ) as jilin_score,
       if(heilongjiang_score in ('--','无数据') and beijing_score != '不参与计算' ,100,heilongjiang_score ) as heilongjiang_score,
       if(shandong_score in ('--','无数据') and beijing_score != '不参与计算' ,100,shandong_score ) as shandong_score,
       if(henan_score in ('--','无数据') and beijing_score != '不参与计算' ,100,henan_score ) as henan_score,
       if(shanggai_score in ('--','无数据') and beijing_score != '不参与计算' ,100,shanggai_score ) as shanggai_score,
       if(jiangsu_score in ('--','无数据') and beijing_score != '不参与计算' ,100,jiangsu_score ) as jiangsu_score,
       if(zhejiang_score in ('--','无数据') and beijing_score != '不参与计算' ,100,zhejiang_score ) as zhejiang_score,
       if(anhui_score in ('--','无数据') and beijing_score != '不参与计算' ,100,anhui_score ) as anhui_score,
       if(fujian_score in ('--','无数据') and beijing_score != '不参与计算' ,100,fujian_score ) as fujian_score,
       if(jiangxi_score in ('--','无数据') and beijing_score != '不参与计算' ,100,jiangxi_score ) as jiangxi_score,
       if(hubei_score in ('--','无数据') and beijing_score != '不参与计算' ,100,hubei_score ) as hubei_score,
       if(hunan_score in ('--','无数据') and beijing_score != '不参与计算' ,100,hunan_score ) as hunan_score,
       if(guangdong_score in ('--','无数据') and beijing_score != '不参与计算' ,100,guangdong_score ) as guangdong_score,
       if(guangxi_score in ('--','无数据') and beijing_score != '不参与计算' ,100,guangxi_score ) as guangxi_score,
       if(hainan_score in ('--','无数据') and beijing_score != '不参与计算' ,100,hainan_score ) as hainan_score,
       if(chongqing_score in ('--','无数据') and beijing_score != '不参与计算' ,100,chongqing_score ) as chongqing_score,
       if(sichuan_score in ('--','无数据') and beijing_score != '不参与计算' ,100,sichuan_score ) as sichuan_score,
       if(guizhou_score in ('--','无数据') and beijing_score != '不参与计算' ,100,guizhou_score ) as guizhou_score,
       if(yunnan_score in ('--','无数据') and beijing_score != '不参与计算' ,100,yunnan_score ) as yunnan_score,
       if(xizang_score in ('--','无数据') and beijing_score != '不参与计算' ,100,xizang_score ) as xizang_score,
       if(shanxi_2_score in ('--','无数据') and beijing_score != '不参与计算' ,100,shanxi_2_score ) as shanxi_2_score,
       if(gansu_score in ('--','无数据') and beijing_score != '不参与计算' ,100,gansu_score ) as gansu_score,
       if(qinghai_score in ('--','无数据') and beijing_score != '不参与计算' ,100,qinghai_score ) as qinghai_score,
       if(ningxia_score in ('--','无数据') and beijing_score != '不参与计算' ,100,ningxia_score ) as ningxia_score,
       if(xinjiang_score in ('--','无数据') and beijing_score != '不参与计算' ,100,xinjiang_score ) as xinjiang_score
from dc_dwd.qyc_temp_02;


-- todo 导入 hive
create table dc_dwd.qyc_temp_03
(
    level_1            string comment '一级-按服务分类',
    level_2            string comment '二级-专业大类',
    level_3            string comment '三级-专业小类 ',
    level_4            string comment '四级-场景',
    level_5            string comment '五级-标准',
    level_6            string comment '六级-指标',
    is_5_window        string comment '是否应用于五大窗口',
    importance         string comment '重要程度',
    index_code         string comment '指标编码',
    index_type         string comment '指标类型',
    target_db_rule     string comment '目标值达标规则',
    target_value       string comment '2024年-目标值',
    index_unit         string comment '指标单位',
    bz_name            string comment '版主',
    is_offline         string comment '是否线下提供',
    jsgs               string comment '计算公式',
    monthid            string comment '填写账期',
    l4_qz              string comment '四级-场景_2',
    l5_qz              string comment '五级-标准_2',
    l6_qz              string comment '六级-指标_2',
    l4_l6_qz           string comment '四-六级综合权重',
    all_nation         string,
    beijing            string,
    tianjin            string,
    hebei              string,
    shanxi_1           string,
    neimenggu          string,
    liaoning           string,
    jilin              string,
    heilongjiang       string,
    shandong           string,
    henan              string,
    shanggai           string,
    jiangsu            string,
    zhejiang           string,
    anhui              string,
    fujian             string,
    jiangxi            string,
    hubei              string,
    hunan              string,
    guangdong          string,
    guangxi            string,
    hainan             string,
    chongqing          string,
    sichuan            string,
    guizhou            string,
    yunnan             string,
    xizang             string,
    shanxi_2           string,
    gansu              string,
    qinghai            string,
    ningxia            string,
    xinjiang           string,
    all_nation_score   string,
    beijing_score      string,
    tianjin_score      string,
    hebei_score        string,
    shanxi_1_score     string,
    neimenggu_score    string,
    liaoning_score     string,
    jilin_score        string,
    heilongjiang_score string,
    shandong_score     string,
    henan_score        string,
    shanggai_score     string,
    jiangsu_score      string,
    zhejiang_score     string,
    anhui_score        string,
    fujian_score       string,
    jiangxi_score      string,
    hubei_score        string,
    hunan_score        string,
    guangdong_score    string,
    guangxi_score      string,
    hainan_score       string,
    chongqing_score    string,
    sichuan_score      string,
    guizhou_score      string,
    yunnan_score       string,
    xizang_score       string,
    shanxi_2_score     string,
    gansu_score        string,
    qinghai_score      string,
    ningxia_score      string,
    xinjiang_score     string
) comment '企业侧' row format delimited fields terminated by ', ' stored as textfile
    location 'hdfs://beh/user/dc_dw/dc_dwd.db/qyc_temp_03';
-- hdfs dfs -put /home/dc_dw/xdc_data/qyc_03_temp.csv /user/dc_dw
load data inpath '/user/dc_dw/qyc_03_temp.csv' overwrite into table dc_dwd.qyc_temp_03;



select level_1,
       level_2,
       level_3,
       level_4,
       level_5,
       level_6,
       is_5_window,
       importance,
       index_code,
       index_type,
       target_db_rule,
       target_value,
       index_unit,
       bz_name,
       is_offline,
       jsgs,
       monthid,
       l4_qz,
       l5_qz,
       l6_qz,
       l4_l6_qz,
       all_nation,
       beijing,
       tianjin,
       hebei,
       shanxi_1,
       neimenggu,
       liaoning,
       jilin,
       heilongjiang,
       shandong,
       henan,
       shanggai,
       jiangsu,
       zhejiang,
       anhui,
       fujian,
       jiangxi,
       hubei,
       hunan,
       guangdong,
       guangxi,
       hainan,
       chongqing,
       sichuan,
       guizhou,
       yunnan,
       xizang,
       shanxi_2,
       gansu,
       qinghai,
       ningxia,
       xinjiang,
       if(all_nation_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,all_nation_score ) as all_nation_score,
       if(beijing_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,beijing_score ) as beijing_score,
       if(tianjin_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,tianjin_score ) as tianjin_score,
       if(hebei_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,hebei_score ) as hebei_score,
       if(shanxi_1_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,shanxi_1_score ) as shanxi_1_score,
       if(neimenggu_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,neimenggu_score ) as neimenggu_score,
       if(liaoning_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,liaoning_score ) as liaoning_score,
       if(jilin_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,jilin_score ) as jilin_score,
       if(heilongjiang_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,heilongjiang_score ) as heilongjiang_score,
       if(shandong_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,shandong_score ) as shandong_score,
       if(henan_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,henan_score ) as henan_score,
       if(shanggai_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,shanggai_score ) as shanggai_score,
       if(jiangsu_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,jiangsu_score ) as jiangsu_score,
       if(zhejiang_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,zhejiang_score ) as zhejiang_score,
       if(anhui_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,anhui_score ) as anhui_score,
       if(fujian_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,fujian_score ) as fujian_score,
       if(jiangxi_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,jiangxi_score ) as jiangxi_score,
       if(hubei_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,hubei_score ) as hubei_score,
       if(hunan_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,hunan_score ) as hunan_score,
       if(guangdong_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,guangdong_score ) as guangdong_score,
       if(guangxi_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,guangxi_score ) as guangxi_score,
       if(hainan_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,hainan_score ) as hainan_score,
       if(chongqing_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,chongqing_score ) as chongqing_score,
       if(sichuan_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,sichuan_score ) as sichuan_score,
       if(guizhou_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,guizhou_score ) as guizhou_score,
       if(yunnan_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,yunnan_score ) as yunnan_score,
       if(xizang_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,xizang_score ) as xizang_score,
       if(shanxi_2_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,shanxi_2_score ) as shanxi_2_score,
       if(gansu_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,gansu_score ) as gansu_score,
       if(qinghai_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,qinghai_score ) as qinghai_score,
       if(ningxia_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,ningxia_score ) as ningxia_score,
       if(xinjiang_score in ('--','无数据') and beijing_score != '不参与计算' and index_type != '体验穿越',100,xinjiang_score ) as xinjiang_score
from dc_dwd.qyc_temp_02;




