set hive.mapred.mode = nonstrict;
set mapreduce.job.queuename = q_dc_dw;


select level_1,
       level_2,
       level_3,
       level_4,
       level_5,
       level_6,
       is_5_window,
       importance,
       index_code,
       index_type,
       target_db_rule,
       target_value,
       index_unit,
       bz_name,
       is_offline,
       jsgs,
       monthid,
       l4_qz,
       l5_qz,
       l6_qz,
       l4_l6_qz,
       all_nation,
       beijing,
       tianjin,
       hebei,
       shanxi_1,
       neimenggu,
       liaoning,
       jilin,
       heilongjiang,
       shandong,
       henan,
       shanggai,
       jiangsu,
       zhejiang,
       anhui,
       fujian,
       jiangxi,
       hubei,
       hunan,
       guangdong,
       guangxi,
       hainan,
       chongqing,
       sichuan,
       guizhou,
       yunnan,
       xizang,
       shanxi_2,
       gansu,
       qinghai,
       ningxia,
       xinjiang,
       all_nation_score,
       beijing_score,
       tianjin_score,
       hebei_score,
       shanxi_1_score,
       neimenggu_score,
       liaoning_score,
       jilin_score,
       heilongjiang_score,
       shandong_score,
       henan_score,
       shanggai_score,
       jiangsu_score,
       zhejiang_score,
       anhui_score,
       fujian_score,
       jiangxi_score,
       hubei_score,
       hunan_score,
       guangdong_score,
       guangxi_score,
       hainan_score,
       chongqing_score,
       sichuan_score,
       guizhou_score,
       yunnan_score,
       xizang_score,
       shanxi_2_score,
       gansu_score,
       qinghai_score,
       ningxia_score,
       xinjiang_score
from dc_dwd.qyc_temp_03;



with t1 as (select level_1,
                   level_2,
                   level_3,
                   level_4,
                   level_5,
                   level_6,
                   is_5_window,
                   importance,
                   index_code,
                   index_type,
                   target_db_rule,
                   target_value,
                   index_unit,
                   bz_name,
                   is_offline,
                   jsgs,
                   monthid,
                   l4_qz,
                   l5_qz,
                   l6_qz,
                   l4_l6_qz,
                   all_nation,
                   beijing,
                   tianjin,
                   hebei,
                   shanxi_1,
                   neimenggu,
                   liaoning,
                   jilin,
                   heilongjiang,
                   shandong,
                   henan,
                   shanggai,
                   jiangsu,
                   zhejiang,
                   anhui,
                   fujian,
                   jiangxi,
                   hubei,
                   hunan,
                   guangdong,
                   guangxi,
                   hainan,
                   chongqing,
                   sichuan,
                   guizhou,
                   yunnan,
                   xizang,
                   shanxi_2,
                   gansu,
                   qinghai,
                   ningxia,
                   xinjiang,
                   all_nation_score * if(index_type = '体验穿越',1,l4_l6_qz)    as all_nation_score,
                   beijing_score * if(index_type = '体验穿越',1,l4_l6_qz)       as beijing_score,
                   tianjin_score * if(index_type = '体验穿越',1,l4_l6_qz)       as tianjin_score,
                   hebei_score * if(index_type = '体验穿越',1,l4_l6_qz)         as hebei_score,
                   shanxi_1_score * if(index_type = '体验穿越',1,l4_l6_qz)      as shanxi_1_score,
                   neimenggu_score * if(index_type = '体验穿越',1,l4_l6_qz)     as neimenggu_score,
                   liaoning_score * if(index_type = '体验穿越',1,l4_l6_qz)      as liaoning_score,
                   jilin_score * if(index_type = '体验穿越',1,l4_l6_qz)         as jilin_score,
                   heilongjiang_score * if(index_type = '体验穿越',1,l4_l6_qz)  as heilongjiang_score,
                   shandong_score * if(index_type = '体验穿越',1,l4_l6_qz)      as shandong_score,
                   henan_score * if(index_type = '体验穿越',1,l4_l6_qz)         as henan_score,
                   shanggai_score * if(index_type = '体验穿越',1,l4_l6_qz)      as shanggai_score,
                   jiangsu_score * if(index_type = '体验穿越',1,l4_l6_qz)       as jiangsu_score,
                   zhejiang_score * if(index_type = '体验穿越',1,l4_l6_qz)      as zhejiang_score,
                   anhui_score * if(index_type = '体验穿越',1,l4_l6_qz)         as anhui_score,
                   fujian_score * if(index_type = '体验穿越',1,l4_l6_qz)        as fujian_score,
                   jiangxi_score * if(index_type = '体验穿越',1,l4_l6_qz)       as jiangxi_score,
                   hubei_score * if(index_type = '体验穿越',1,l4_l6_qz)         as hubei_score,
                   hunan_score * if(index_type = '体验穿越',1,l4_l6_qz)         as hunan_score,
                   guangdong_score * if(index_type = '体验穿越',1,l4_l6_qz)     as guangdong_score,
                   guangxi_score * if(index_type = '体验穿越',1,l4_l6_qz)       as guangxi_score,
                   hainan_score * if(index_type = '体验穿越',1,l4_l6_qz)        as hainan_score,
                   chongqing_score * if(index_type = '体验穿越',1,l4_l6_qz)     as chongqing_score,
                   sichuan_score * if(index_type = '体验穿越',1,l4_l6_qz)       as sichuan_score,
                   guizhou_score * if(index_type = '体验穿越',1,l4_l6_qz)       as guizhou_score,
                   yunnan_score * if(index_type = '体验穿越',1,l4_l6_qz)        as yunnan_score,
                   xizang_score * if(index_type = '体验穿越',1,l4_l6_qz)        as xizang_score,
                   shanxi_2_score * if(index_type = '体验穿越',1,l4_l6_qz)      as shanxi_2_score,
                   gansu_score * if(index_type = '体验穿越',1,l4_l6_qz)         as gansu_score,
                   qinghai_score * if(index_type = '体验穿越',1,l4_l6_qz)       as qinghai_score,
                   ningxia_score * if(index_type = '体验穿越',1,l4_l6_qz)       as ningxia_score,
                   xinjiang_score * if(index_type = '体验穿越',1,l4_l6_qz)      as xinjiang_score
            from dc_dwd.qyc_temp_03),
     t2 as
         (select level_1,
                 level_2,
                 level_3,
                 level_4,
                 level_5,
                 level_6,
                 is_5_window,
                 importance,
                 index_code,
                 index_type,
                 target_db_rule,
                 target_value,
                 index_unit,
                 bz_name,
                 is_offline,
                 jsgs,
                 monthid,
                 l4_qz,
                 l5_qz,
                 l6_qz,
                 l4_l6_qz,
                 all_nation,
                 beijing,
                 tianjin,
                 hebei,
                 shanxi_1,
                 neimenggu,
                 liaoning,
                 jilin,
                 heilongjiang,
                 shandong,
                 henan,
                 shanggai,
                 jiangsu,
                 zhejiang,
                 anhui,
                 fujian,
                 jiangxi,
                 hubei,
                 hunan,
                 guangdong,
                 guangxi,
                 hainan,
                 chongqing,
                 sichuan,
                 guizhou,
                 yunnan,
                 xizang,
                 shanxi_2,
                 gansu,
                 qinghai,
                 ningxia,
                 xinjiang,
                 sum(all_nation_score) over (partition by level_3 )   as all_nation_score,
                 sum(beijing_score) over (partition by level_3 )      as beijing_score,
                 sum(tianjin_score) over (partition by level_3 )      as tianjin_score,
                 sum(hebei_score) over (partition by level_3 )        as hebei_score,
                 sum(shanxi_1_score) over (partition by level_3 )     as shanxi_1_score,
                 sum(neimenggu_score) over (partition by level_3 )    as neimenggu_score,
                 sum(liaoning_score) over (partition by level_3 )     as liaoning_score,
                 sum(jilin_score) over (partition by level_3 )        as jilin_score,
                 sum(heilongjiang_score) over (partition by level_3 ) as heilongjiang_score,
                 sum(shandong_score) over (partition by level_3 )     as shandong_score,
                 sum(henan_score) over (partition by level_3 )        as henan_score,
                 sum(shanggai_score) over (partition by level_3 )     as shanggai_score,
                 sum(jiangsu_score) over (partition by level_3 )      as jiangsu_score,
                 sum(zhejiang_score) over (partition by level_3 )     as zhejiang_score,
                 sum(anhui_score) over (partition by level_3 )        as anhui_score,
                 sum(fujian_score) over (partition by level_3 )       as fujian_score,
                 sum(jiangxi_score) over (partition by level_3 )      as jiangxi_score,
                 sum(hubei_score) over (partition by level_3 )        as hubei_score,
                 sum(hunan_score) over (partition by level_3 )        as hunan_score,
                 sum(guangdong_score) over (partition by level_3 )    as guangdong_score,
                 sum(guangxi_score) over (partition by level_3 )      as guangxi_score,
                 sum(hainan_score) over (partition by level_3 )       as hainan_score,
                 sum(chongqing_score) over (partition by level_3 )    as chongqing_score,
                 sum(sichuan_score) over (partition by level_3 )      as sichuan_score,
                 sum(guizhou_score) over (partition by level_3 )      as guizhou_score,
                 sum(yunnan_score) over (partition by level_3 )       as yunnan_score,
                 sum(xizang_score) over (partition by level_3 )       as xizang_score,
                 sum(shanxi_2_score) over (partition by level_3 )     as shanxi_2_score,
                 sum(gansu_score) over (partition by level_3 )        as gansu_score,
                 sum(qinghai_score) over (partition by level_3 )      as qinghai_score,
                 sum(ningxia_score) over (partition by level_3 )      as ningxia_score,
                 sum(xinjiang_score) over (partition by level_3 )     as xinjiang_score
          from t1)
select distinct level_1,
                level_2,
                level_3,
                round(all_nation_score, 6)   as all_nation_score,
                round(beijing_score, 6)      as beijing_score,
                round(tianjin_score, 6)      as tianjin_score,
                round(hebei_score, 6)        as hebei_score,
                round(shanxi_1_score, 6)     as shanxi_1_score,
                round(neimenggu_score, 6)    as neimenggu_score,
                round(liaoning_score, 6)     as liaoning_score,
                round(jilin_score, 6)        as jilin_score,
                round(heilongjiang_score, 6) as heilongjiang_score,
                round(shandong_score, 6)     as shandong_score,
                round(henan_score, 6)        as henan_score,
                round(shanggai_score, 6)     as shanggai_score,
                round(jiangsu_score, 6)      as jiangsu_score,
                round(zhejiang_score, 6)     as zhejiang_score,
                round(anhui_score, 6)        as anhui_score,
                round(fujian_score, 6)       as fujian_score,
                round(jiangxi_score, 6)      as jiangxi_score,
                round(hubei_score, 6)        as hubei_score,
                round(hunan_score, 6)        as hunan_score,
                round(guangdong_score, 6)    as guangdong_score,
                round(guangxi_score, 6)      as guangxi_score,
                round(hainan_score, 6)       as hainan_score,
                round(chongqing_score, 6)    as chongqing_score,
                round(sichuan_score, 6)      as sichuan_score,
                round(guizhou_score, 6)      as guizhou_score,
                round(yunnan_score, 6)       as yunnan_score,
                round(xizang_score, 6)       as xizang_score,
                round(shanxi_2_score, 6)     as shanxi_2_score,
                round(gansu_score, 6)        as gansu_score,
                round(qinghai_score, 6)      as qinghai_score,
                round(ningxia_score, 6)      as ningxia_score,
                round(xinjiang_score, 6)     as xinjiang_score
from t2;