set hive.mapred.mode = nonstrict;
set mapreduce.job.queuename = q_dc_dw;


drop table dc_dwd.bus_temp_base;
create table dc_dwd.bus_temp_base
(
    level_1      string comment '一级-按服务分类',
    level_2      string comment '二级-专业大类',
    level_3      string comment '三级专业小类',
    level_4      string comment '四级-场景',
    level_5      string comment '五级-标准',
    level_6      string comment '六级-指标',
    is_5window   string comment '',
    importance   string comment '',
    index_code   string comment '',
    index_type   string comment '',
    target_rule  string comment '',
    target_value string comment '',
    index_unit   string comment '',
    banzhu       string comment '',
    month_id     string comment '',
    l4_qz        string comment '',
    l5_qz        string comment '',
    l6_qz        string comment '',
    4_6_qz       string comment '',
    all_nation   string comment '',
    beijing      string comment '',
    tianjin      string comment '',
    hebei        string comment '',
    shanxi_1     string comment '山西',
    neimenggu    string comment '',
    liaoning     string comment '',
    jilin        string comment '',
    heilongjiang string comment '',
    shandong     string comment '',
    henan        string comment '',
    shanggai     string comment '',
    jiangsu      string comment '',
    zhejiang     string comment '',
    anhui        string comment '',
    fujian       string comment '',
    jiangxi      string comment '',
    hubei        string comment '',
    hunan        string comment '',
    guangdong    string comment '',
    guangxi      string comment '',
    hainan       string comment '',
    chongqing    string comment '',
    sichuan      string comment '',
    guizhou      string comment '',
    yunnan       string comment '',
    xizang       string comment '',
    shanxi_2     string comment '陕西',
    gansu        string comment '',
    qinghai      string comment '',
    ningxia      string comment '',
    xinjiang     string comment ''

) row format delimited fields terminated by ',' stored as textfile
    location 'hdfs://beh/user/dc_dw/dc_dwd.db/bus_temp_base';
-- hdfs dfs -put /home/dc_dw/xdc_data/temp_1.csv /user/dc_dw
load data inpath '/user/dc_dw/temp_1.csv' overwrite into table dc_dwd.bus_temp_base;
select *
from dc_Dwd.bus_temp_base;



set hive.mapred.mode = nonstrict;
set mapreduce.job.queuename = q_dc_dw;
-- 100
with t1 as (select level_1,
                   level_2,
                   level_3,
                   level_4,
                   level_5,
                   level_6,
                   is_5window,
                   importance,
                   index_code,
                   index_type,
                   target_rule,
                   target_value,
                   index_unit,
                   banzhu,
                   month_id,
                   l4_qz,
                   l5_qz,
                   l6_qz,
                   4_6_qz,
                   if(l6_qz = '扣分项' and all_nation = '', 0, all_nation)   as all_nation,
                   if(l6_qz = '扣分项' and all_nation = '', 0, beijing)      as beijing,
                   if(l6_qz = '扣分项' and all_nation = '', 0, tianjin)      as tianjin,
                   if(l6_qz = '扣分项' and all_nation = '', 0, hebei)        as hebei,
                   if(l6_qz = '扣分项' and all_nation = '', 0, shanxi_1)     as shanxi_1,
                   if(l6_qz = '扣分项' and all_nation = '', 0, neimenggu)    as neimenggu,
                   if(l6_qz = '扣分项' and all_nation = '', 0, liaoning)     as liaoning,
                   if(l6_qz = '扣分项' and all_nation = '', 0, jilin)        as jilin,
                   if(l6_qz = '扣分项' and all_nation = '', 0, heilongjiang) as heilongjiang,
                   if(l6_qz = '扣分项' and all_nation = '', 0, shandong)     as shandong,
                   if(l6_qz = '扣分项' and all_nation = '', 0, henan)        as henan,
                   if(l6_qz = '扣分项' and all_nation = '', 0, shanggai)     as shanggai,
                   if(l6_qz = '扣分项' and all_nation = '', 0, jiangsu)      as jiangsu,
                   if(l6_qz = '扣分项' and all_nation = '', 0, zhejiang)     as zhejiang,
                   if(l6_qz = '扣分项' and all_nation = '', 0, anhui)        as anhui,
                   if(l6_qz = '扣分项' and all_nation = '', 0, fujian)       as fujian,
                   if(l6_qz = '扣分项' and all_nation = '', 0, jiangxi)      as jiangxi,
                   if(l6_qz = '扣分项' and all_nation = '', 0, hubei)        as hubei,
                   if(l6_qz = '扣分项' and all_nation = '', 0, hunan)        as hunan,
                   if(l6_qz = '扣分项' and all_nation = '', 0, guangdong)    as guangdong,
                   if(l6_qz = '扣分项' and all_nation = '', 0, guangxi)      as guangxi,
                   if(l6_qz = '扣分项' and all_nation = '', 0, hainan)       as hainan,
                   if(l6_qz = '扣分项' and all_nation = '', 0, chongqing)    as chongqing,
                   if(l6_qz = '扣分项' and all_nation = '', 0, sichuan)      as sichuan,
                   if(l6_qz = '扣分项' and all_nation = '', 0, guizhou)      as guizhou,
                   if(l6_qz = '扣分项' and all_nation = '', 0, yunnan)       as yunnan,
                   if(l6_qz = '扣分项' and all_nation = '', 0, xizang)       as xizang,
                   if(l6_qz = '扣分项' and all_nation = '', 0, shanxi_2)     as shanxi_2,
                   if(l6_qz = '扣分项' and all_nation = '', 0, gansu)        as gansu,
                   if(l6_qz = '扣分项' and all_nation = '', 0, qinghai)      as qinghai,
                   if(l6_qz = '扣分项' and all_nation = '', 0, ningxia)      as ningxia,
                   if(l6_qz = '扣分项' and all_nation = '', 0, xinjiang)     as xinjiang
            from dc_dwd.bus_temp_base),
     t2 as (select level_1,
                   level_2,
                   level_3,
                   level_4,
                   level_5,
                   level_6,
                   is_5window,
                   importance,
                   index_code,
                   index_type,
                   target_rule,
                   target_value,
                   index_unit,
                   banzhu,
                   month_id,
                   l4_qz,
                   l5_qz,
                   l6_qz,
                   4_6_qz,
                   if(all_nation is null or all_nation in ('', '无数据'), 100, all_nation)       as all_nation,
                   if(beijing is null or beijing in ('', '无数据'), 100, beijing)                as beijing,
                   if(tianjin is null or tianjin in ('', '无数据'), 100, tianjin)                as tianjin,
                   if(hebei is null or hebei in ('', '无数据'), 100, hebei)                      as hebei,
                   if(shanxi_1 is null or shanxi_1 in ('', '无数据'), 100, shanxi_1)             as shanxi_1,
                   if(neimenggu is null or neimenggu in ('', '无数据'), 100, neimenggu)          as neimenggu,
                   if(liaoning is null or liaoning in ('', '无数据'), 100, liaoning)             as liaoning,
                   if(jilin is null or jilin in ('', '无数据'), 100, jilin)                      as jilin,
                   if(heilongjiang is null or heilongjiang in ('', '无数据'), 100, heilongjiang) as heilongjiang,
                   if(shandong is null or shandong in ('', '无数据'), 100, shandong)             as shandong,
                   if(henan is null or henan in ('', '无数据'), 100, henan)                      as henan,
                   if(shanggai is null or shanggai in ('', '无数据'), 100, shanggai)             as shanggai,
                   if(jiangsu is null or jiangsu in ('', '无数据'), 100, jiangsu)                as jiangsu,
                   if(zhejiang is null or zhejiang in ('', '无数据'), 100, zhejiang)             as zhejiang,
                   if(anhui is null or anhui in ('', '无数据'), 100, anhui)                      as anhui,
                   if(fujian is null or fujian in ('', '无数据'), 100, fujian)                   as fujian,
                   if(jiangxi is null or jiangxi in ('', '无数据'), 100, jiangxi)                as jiangxi,
                   if(hubei is null or hubei in ('', '无数据'), 100, hubei)                      as hubei,
                   if(hunan is null or hunan in ('', '无数据'), 100, hunan)                      as hunan,
                   if(guangdong is null or guangdong in ('', '无数据'), 100, guangdong)          as guangdong,
                   if(guangxi is null or guangxi in ('', '无数据'), 100, guangxi)                as guangxi,
                   if(hainan is null or hainan in ('', '无数据'), 100, hainan)                   as hainan,
                   if(chongqing is null or chongqing in ('', '无数据'), 100, chongqing)          as chongqing,
                   if(sichuan is null or sichuan in ('', '无数据'), 100, sichuan)                as sichuan,
                   if(guizhou is null or guizhou in ('', '无数据'), 100, guizhou)                as guizhou,
                   if(yunnan is null or yunnan in ('', '无数据'), 100, yunnan)                   as yunnan,
                   if(xizang is null or xizang in ('', '无数据'), 100, xizang)                   as xizang,
                   if(shanxi_2 is null or shanxi_2 in ('', '无数据'), 100, shanxi_2)             as shanxi_2,
                   if(gansu is null or gansu in ('', '无数据'), 100, gansu)                      as gansu,
                   if(qinghai is null or qinghai in ('', '无数据'), 100, qinghai)                as qinghai,
                   if(ningxia is null or ningxia in ('', '无数据'), 100, ningxia)                as ningxia,
                   if(xinjiang is null or xinjiang in ('', '无数据'), 100, xinjiang)             as xinjiang

            from t1),
     t3 as (select level_1,
                   level_2,
                   level_3,
                   level_4,
                   level_5,
                   level_6,
                   is_5window,
                   importance,
                   index_code,
                   index_type,
                   target_rule,
                   target_value,
                   index_unit,
                   banzhu,
                   month_id,
                   l4_qz,
                   l5_qz,
                   l6_qz,
                   4_6_qz,
                   all_nation * 4_6_qz   as all_nation,
                   beijing * 4_6_qz      as beijing,
                   tianjin * 4_6_qz      as tianjin,
                   hebei * 4_6_qz        as hebei,
                   shanxi_1 * 4_6_qz     as shanxi_1,
                   neimenggu * 4_6_qz    as neimenggu,
                   liaoning * 4_6_qz     as liaoning,
                   jilin * 4_6_qz        as jilin,
                   heilongjiang * 4_6_qz as heilongjiang,
                   shandong * 4_6_qz     as shandong,
                   henan * 4_6_qz        as henan,
                   shanggai * 4_6_qz     as shanggai,
                   jiangsu * 4_6_qz      as jiangsu,
                   zhejiang * 4_6_qz     as zhejiang,
                   anhui * 4_6_qz        as anhui,
                   fujian * 4_6_qz       as fujian,
                   jiangxi * 4_6_qz      as jiangxi,
                   hubei * 4_6_qz        as hubei,
                   hunan * 4_6_qz        as hunan,
                   guangdong * 4_6_qz    as guangdong,
                   guangxi * 4_6_qz      as guangxi,
                   hainan * 4_6_qz       as hainan,
                   chongqing * 4_6_qz    as chongqing,
                   sichuan * 4_6_qz      as sichuan,
                   guizhou * 4_6_qz      as guizhou,
                   yunnan * 4_6_qz       as yunnan,
                   xizang * 4_6_qz       as xizang,
                   shanxi_2 * 4_6_qz     as shanxi_2,
                   gansu * 4_6_qz        as gansu,
                   qinghai * 4_6_qz      as qinghai,
                   ningxia * 4_6_qz      as ningxia,
                   xinjiang * 4_6_qz     as xinjiang
            from t2),
     t4 as (select level_1,
                   level_2,
                   level_3,
                   level_4,
                   level_5,
                   level_6,
                   is_5window,
                   importance,
                   index_code,
                   index_type,
                   target_rule,
                   target_value,
                   index_unit,
                   banzhu,
                   month_id,
                   l4_qz,
                   l5_qz,
                   l6_qz,
                   4_6_qz,
                   sum(all_nation) over (partition by level_3)   as all_nation,
                   sum(beijing) over (partition by level_3)      as beijing,
                   sum(tianjin) over (partition by level_3)      as tianjin,
                   sum(hebei) over (partition by level_3)        as hebei,
                   sum(shanxi_1) over (partition by level_3)     as shanxi_1,
                   sum(neimenggu) over (partition by level_3)    as neimenggu,
                   sum(liaoning) over (partition by level_3)     as liaoning,
                   sum(jilin) over (partition by level_3)        as jilin,
                   sum(heilongjiang) over (partition by level_3) as heilongjiang,
                   sum(shandong) over (partition by level_3)     as shandong,
                   sum(henan) over (partition by level_3)        as henan,
                   sum(shanggai) over (partition by level_3)     as shanggai,
                   sum(jiangsu) over (partition by level_3)      as jiangsu,
                   sum(zhejiang) over (partition by level_3)     as zhejiang,
                   sum(anhui) over (partition by level_3)        as anhui,
                   sum(fujian) over (partition by level_3)       as fujian,
                   sum(jiangxi) over (partition by level_3)      as jiangxi,
                   sum(hubei) over (partition by level_3)        as hubei,
                   sum(hunan) over (partition by level_3)        as hunan,
                   sum(guangdong) over (partition by level_3)    as guangdong,
                   sum(guangxi) over (partition by level_3)      as guangxi,
                   sum(hainan) over (partition by level_3)       as hainan,
                   sum(chongqing) over (partition by level_3)    as chongqing,
                   sum(sichuan) over (partition by level_3)      as sichuan,
                   sum(guizhou) over (partition by level_3)      as guizhou,
                   sum(yunnan) over (partition by level_3)       as yunnan,
                   sum(xizang) over (partition by level_3)       as xizang,
                   sum(shanxi_2) over (partition by level_3)     as shanxi_2,
                   sum(gansu) over (partition by level_3)        as gansu,
                   sum(qinghai) over (partition by level_3)      as qinghai,
                   sum(ningxia) over (partition by level_3)      as ningxia,
                   sum(xinjiang) over (partition by level_3)     as xinjiang
            from t3)
select distinct level_1,
                level_2,
                level_3,
                round(all_nation,6) as all_nation,
                round(beijing,6) as beijing,
                round(tianjin,6) as tianjin,
                round(hebei,6) as hebei,
                round(shanxi_1,6) as shanxi_1,
                round(neimenggu,6) as neimenggu,
                round(liaoning,6) as liaoning,
                round(jilin,6) as jilin,
                round(heilongjiang,6) as heilongjiang,
                round(shandong,6) as shandong,
                round(henan,6) as henan,
                round(shanggai,6) as shanggai,
                round(jiangsu,6) as jiangsu,
                round(zhejiang,6) as zhejiang,
                round(anhui,6) as anhui,
                round(fujian,6) as fujian,
                round(jiangxi,6) as jiangxi,
                round(hubei,6) as hubei,
                round(hunan,6) as hunan,
                round(guangdong,6) as guangdong,
                round(guangxi,6) as guangxi,
                round(hainan,6) as hainan,
                round(chongqing,6) as chongqing,
                round(sichuan,6) as sichuan,
                round(guizhou,6) as guizhou,
                round(yunnan,6) as yunnan,
                round(xizang,6) as xizang,
                round(shanxi_2,6) as shanxi_2,
                round(gansu,6) as gansu,
                round(qinghai,6) as qinghai,
                round(ningxia,6) as ningxia,
                round(xinjiang,6) as xinjiang
from t4;